name: 'docker-automatic-push'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
  
  build:
    needs: check-out
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: DockerHub login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v1

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image
        run: DOCKER_BUILDKIT=0  docker build -t simple-warehouse ../Dockerfile
      - name: Test run container
        run: docker container run --rm simple-warehouse
  Push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push to Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-warehouse:latest

    
