name: 'docker-automatic-push'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
  build:
    runs-on: docker
    steps:
      - name: Build image
        run: docker build -t item-api:test .
      # - name: Build env
      #   run:
      #     command: pip install -r requirements.txt

  # automatic docker push:
  #   name: push image to dockerhub
  #   runs-on: ubuntu-latest
      # - name: Docker login
      #   uses: docker/login-action
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: YuyaRa/item-api
      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

    
